// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActorsConfig = { series_index: number, day: string, offset: number, limit: number, };
