// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterSource } from "./FilterSource";

export type Breakdown = { source: FilterSource, key: string, limit: number, };
