// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastN } from "./LastN";

export type DateRange = { from: string | null, to: string | null, last_n: LastN | null, };
