// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterOperator } from "./FilterOperator";
import type { FilterSource } from "./FilterSource";

export type Filter = { source: FilterSource, key: string, operator: FilterOperator, value: any, };
