// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterOperator = { "op": "exact" } | { "op": "iexact" } | { "op": "not_equal" } | { "op": "contains" } | { "op": "not_contains" } | { "op": "icontains" } | { "op": "is_set" } | { "op": "is_not_set" } | { "op": "eq" } | { "op": "gt" } | { "op": "lt" } | { "op": "gte" } | { "op": "lte" } | { "op": "between" } | { "op": "in" } | { "op": "not_in" };
