// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Variant } from "./Variant";

export type FlagDef = { key: string, active: boolean, rollout_percentage: number, variants: Array<Variant>, };
