// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunnelAttribution } from "./FunnelAttribution";
import type { FunnelExclusion } from "./FunnelExclusion";
import type { FunnelOrder } from "./FunnelOrder";

export type FunnelConfig = { order_type: FunnelOrder, conversion_window_seconds: number | null, exclusions: Array<FunnelExclusion>, attribution: FunnelAttribution, };
