// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LastN = { "unit": "h", "value": number } | { "unit": "d", "value": number } | { "unit": "w", "value": number } | { "unit": "m", "value": number };
