// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventMatch } from "./EventMatch";
import type { LifecyclePeriod } from "./LifecyclePeriod";

export type LifecycleConfig = { event: EventMatch, prior_period: LifecyclePeriod, };
