// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorAgg } from "./ActorAgg";

export type Math = { "type": "total" } | { "type": "dau" } | { "type": "wau" } | { "type": "mau" } | { "type": "unique_sessions" } | { "type": "first_time" } | { "type": "property_sum", "value": string } | { "type": "property_avg", "value": string } | { "type": "property_min", "value": string } | { "type": "property_max", "value": string } | { "type": "property_median", "value": string } | { "type": "property_p75", "value": string } | { "type": "property_p90", "value": string } | { "type": "property_p95", "value": string } | { "type": "property_p99", "value": string } | { "type": "count_per_actor", "value": ActorAgg };
