// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupOp } from "./GroupOp";
import type { GroupOrFilter } from "./GroupOrFilter";

export type PropertyGroup = { op: GroupOp, values: Array<GroupOrFilter>, };
