// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorsConfig } from "./ActorsConfig";
import type { Breakdown } from "./Breakdown";
import type { DateRange } from "./DateRange";
import type { Formula } from "./Formula";
import type { FunnelConfig } from "./FunnelConfig";
import type { Interval } from "./Interval";
import type { LifecycleConfig } from "./LifecycleConfig";
import type { PropertyGroup } from "./PropertyGroup";
import type { QueryKind } from "./QueryKind";
import type { RetentionConfig } from "./RetentionConfig";
import type { Series } from "./Series";
import type { SqlConfig } from "./SqlConfig";
import type { StickinessConfig } from "./StickinessConfig";

export type Query = { kind: QueryKind, series: Array<Series>, filters: PropertyGroup, breakdown: Breakdown | null, breakdown2: Breakdown | null, range: DateRange, interval: Interval, formulas: Array<Formula>, funnel_config: FunnelConfig | null, retention_config: RetentionConfig | null, lifecycle_config: LifecycleConfig | null, stickiness_config: StickinessConfig | null, actors_config: ActorsConfig | null, sql_config: SqlConfig | null, };
