// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aliases are deserialize-only, so the wire output and the generated TS types
 * are unchanged. They exist because `meta.kind` comes back lowercase
 * ("trends"), and an API that will not accept the spelling it just emitted is
 * a trap for anyone hand-writing a query.
 */
export type QueryKind = "Trends" | "Funnels" | "Retention" | "Lifecycle" | "Stickiness" | "Actors" | "Sql";
