// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryMeta } from "./QueryMeta";
import type { SeriesResult } from "./SeriesResult";

export type QueryResponse = { results: Array<SeriesResult>, meta: QueryMeta, };
