// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventMatch } from "./EventMatch";
import type { RetentionPeriod } from "./RetentionPeriod";
import type { RetentionType } from "./RetentionType";

export type RetentionConfig = { cohort_event: EventMatch, retention_event: EventMatch, retention_type: RetentionType, period: RetentionPeriod, total_periods: number, };
