// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventMatch } from "./EventMatch";
import type { Math } from "./Math";

export type Series = { event: EventMatch, math: Math, };
