// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataPoint } from "./DataPoint";

export type SeriesResult = { label: string, data: Array<DataPoint>, breakdown_value: string | null, };
