// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Stats = { total_events: number, unique_persons: number, events_24h: number, };
