// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventMatch } from "./EventMatch";

export type StickinessConfig = { event: EventMatch, window_days: number, };
