// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One variant of a multivariate flag. `rollout` values across a flag's
 * variants are cumulative buckets summing to ~100.
 */
export type Variant = { key: string, rollout: number, };
